--Group 2 - BI11:
-- Muhammad Rafli (2602111181)
-- Muhammad Andrie Syaamil (2602110563)
-- Justin (2602111950)
-- Luthfi Athallah Rakasiwi (2602109574)


CREATE DATABASE FuniMaZion

USE FuniMaZion

CREATE TABLE MsCity(
	CityID VARCHAR(10) PRIMARY KEY CHECK (CityID LIKE 'CI[0-9][0-9][0-9]') NOT NULL,
	CityName VARCHAR(20) NOT NULL
)

CREATE TABLE MsStaff ( 
	StaffID VARCHAR(10) PRIMARY KEY CHECK (StaffID LIKE 'SF[0-9][0-9][0-9]') NOT NULL,  
	StaffName VARCHAR(50) NOT  NULL,
	CityID VARCHAR(10) FOREIGN KEY REFERENCES MsCity(CityID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	StaffGender VARCHAR(10) CHECK (StaffGender IN ('Male','Female') ) NOT NULL,
	StaffEmail VARCHAR(MAX) NOT NULL,
	StaffPassword  VARCHAR(MAX) CHECK (LEN(StaffPassword) > = 8) NOT NULL,
	StaffDOB DATE CHECK (YEAR(StaffDOB) < 2000) NOT NULL
)

CREATE TABLE MsAnimeGenre (
	AnimeGenreID VARCHAR(10) PRIMARY KEY CHECK (AnimeGenreID LIKE 'GE[0-9][0-9][0-9]') NOT NULL,
	AnimeGenreName VARCHAR (50) NOT NULL
)

	
CREATE TABLE MsAnime (
  	AnimeID VARCHAR(10) PRIMARY KEY Check (AnimeID like 'AN[0-9][0-9][0-9]') NOT NULL,
  	AnimeGenreID VARCHAR(10)FOREIGN KEY REFERENCES MsAnimeGenre(AnimeGenreID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  	AnimeName VARCHAR(MAX) NOT NULL,
  	AnimeSubscribePrice INT NOT NULL,
  	AnimeDescription VARCHAR(MAX) NOT NULL,
  	AnimeMinimumAge INT CHECK (AnimeMinimumAge BETWEEN 0 AND 25) NOT NULL
)

CREATE TABLE MsCustomer ( 
  CustomerID VARCHAR(10)PRIMARY KEY Check (CustomerID LIKE 'CU[0-9][0-9][0-9]') NOT NULL,
  CustomerName VARCHAR(50) NOT NULL,
  CityID VARCHAR(10) FOREIGN KEY REFERENCES MsCity(CityID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
  CustomerGender VARCHAR(10) CHECK (CustomerGender IN ('Male','Female') ) NOT NULL,
  CustomerEmail VARCHAR(MAX) CHECK (CustomerEmail LIKE '%@gmail.com') NOT NULL,
  CustomerPassword VARCHAR(MAX) CHECK (LEN(CustomerPassword) > = 8) NOT NULL,
  CustomerDOB DATE NOT NULL
)

CREATE TABLE MsStudio ( 
    StudioID VARCHAR (10) PRIMARY KEY Check (StudioID LIKE 'SD[0-9][0-9][0-9]') NOT NULL,
    StudioName VARCHAR(MAX) NOT NULL,
    CityID VARCHAR(10) FOREIGN KEY REFERENCES MsCity(CityID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL, 
)

CREATE TABLE PurchaseHeader (
 	PurchaseID VARCHAR(10) PRIMARY KEY Check (PurchaseID LIKE 'PU[0-9][0-9][0-9]') NOT NULL,
  	StaffID VARCHAR(10)FOREIGN KEY REFERENCES MsStaff(StaffID) NOT NULL,
  	StudioID VARCHAR(10)FOREIGN KEY REFERENCES MsStudio(StudioID)  NOT NULL,
  	PurchaseDate DATE NOT NULL
)

CREATE TABLE PurchaseDetail(
	PurchaseID VARCHAR(10) FOREIGN KEY REFERENCES PurchaseHeader(PurchaseID) NOT NULL,
  	AnimeID VARCHAR(10)FOREIGN KEY REFERENCES MsAnime(AnimeID)  NOT NULL,
	PRIMARY KEY(PurchaseID,AnimeID)
)

CREATE TABLE SalesHeader (
	SalesID VARCHAR(10) PRIMARY KEY CHECK (SalesID LIKE 'SA[0-9][0-9][0-9]') NOT NULL,
	CustomerID VARCHAR(10) FOREIGN KEY REFERENCES MsCustomer(CustomerID) NOT NULL,
	SalesDate DATE NOT NULL,
	SalesMethod VARCHAR (10) CHECK (SalesMethod IN ('Credit','Debit')) NOT NULL
)

CREATE TABLE SalesDetail(
	SalesID VARCHAR(10) FOREIGN KEY REFERENCES SalesHeader(SalesID) NOT NULL,
	AnimeID VARCHAR (10)FOREIGN KEY REFERENCES MsAnime(AnimeID) NOT NULL,
	PRIMARY KEY(SalesID,AnimeID),
	SalesAnimeDuration INT NOT NULL
)

